# Generated by Django 4.2.6 on 2023-10-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الثلاثي')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الجوال')),
                ('country', models.CharField(max_length=50, verbose_name='الدولة')),
                ('address', models.TextField(verbose_name='العنوان')),
            ],
        ),
    ]
